### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by IonicaBizau**
📝

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks! you're awesome!

**Comment by IonicaBizau** [comment]
@jonschlinkert This is my go-to place to copy the days of the week from. And often, I copied them from the example, in non-`npm` contexts, and at some point I realized there was a typo. 😂 

You're welcome!

**Comment by IonicaBizau** [comment]
You may want to `npm publish` it, so the change will appear on `npm` as well. I usually do `npmjs.com/days` 😁

**Comment by jonschlinkert** [comment]
done! and git tagged.

> at some point I realized there was a typo

well at least someone did! lol I wonder how many times I've looked at this and not noticed. the funny thing is, I was an English major in college lol.

sorry about that, and thanks again!

**Pull request merged**
